server:
  port: "8888"

spring:
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url: "jdbc:postgresql://db:5432/orders"
    username: "admin"
    password: "Zxcv1234"

logging:
  level:
    org.springframework.data: warn
    org.hibernate: warn
    orders: debug